### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by nekocode** [maoruibin/ViewController#3]
很明显，你想做的事（所谓的 Layout 解块）和 ViewGroup 重叠了。你自己创造了个所谓「ViewController」的概念，然而这东西不和 View/Fragment 一样能融入到 Android 的开发生态中。

更好的解块法是当然直接继承 ViewGroup（当然你要加 fillData 方法也是行的）。

**Comment by maoruibin** [comment]
是的，使用vg也是可以的，关键在于代码分块这种思路，同样的思路，不同的实现方式都可以做到，只是我觉得这种方式更容易使用和理解。
